### ISSUE TITLE
How to pass custom host?

### ISSUE THREAD

**Issue by Munfred** [Munfred/scdefg#19]
It seems click is having trouble parsing a host like '0.0.0.0' , but 'localhost' (the default) works. Need to fix

**Comment by nuin** [comment]
It worked fine for me, when I tried on a fresh machine that hadn't had the program installed before. I tried with the versions in the requirements and with new versions of Flask and Click, and I got good results, testing both `localhost` and 0.0.0.0. All tests were performed with a virtual environment.

With the release of Flask 2.0, I would test this version with your current input files and upgrade to it. It feels faster, both startup time and usage.

**Comment by Munfred** [comment]
added flask 2.0, host is working
